default_platform(:ios)

app_identifier_prod = "ai.tabby.fluttersdk"
app_store_connect_api_key_id = "6WK27WDACV"
app_store_connect_api_key_issuer_id = "0f3cf82f-22f3-4ddb-ae8b-a6d39e797d06"
default_xcodeproj = "./Runner.xcodeproj"
default_target_name = "Runner"

platform :ios do
  desc "Description of what the lane does"
  lane :upload_testflight do |options|
    puts("🚀 Uploading to TestFlight has started")

    # AUTHENTICATION TO APPSTORE CONNECT
    puts("🔐 Trying to access AppStore Connect API Key")
    api_key = app_store_connect_api_key(
      key_id: app_store_connect_api_key_id,
      issuer_id: app_store_connect_api_key_issuer_id,
      key_filepath: ENV["APPSTORE_API_KEY"],
      duration: 1200,
      in_house: false
    )

    puts("🚀 Uploading to TestFlight")
    puts "🔑 FASTLANE IPA_PATH found at:\n#{ENV["IPA_PATH"]}"

    app_version_str = options[:app_version]
    build_number_str = options[:build_number]
    puts("🏁 build number: #{build_number_str}")
    puts("🏁 app version: #{app_version_str}")

    upload_to_testflight(
      api_key: api_key,
      team_id: 121945547,
      app_version: app_version_str,
      build_number: build_number_str,
      skip_waiting_for_build_processing: true,
      ipa: ENV["IPA_PATH"]
  )
  
  end
end
